set encoding=utf-8
set fileencoding=utf-8
set number                      " Display line numbers beside buffer
set nocompatible                " Don't maintain compatibilty with Vi.
set hidden                      " Allow buffer change w/o saving
set lazyredraw                  " Don't update while executing macros
set backspace=indent,eol,start  " Sane backspace behavior
set history=1000                " Remember last 1000 commands
set scrolloff=4                 " Keep at least 4 lines below cursor

nmap 0 ^
nmap 0 $

" Move up and down by visible lines if current line is wrapped
nmap j gj
nmap k gk

imap jk <esc>
imap kj <esc>

let mapleader = "\<Space>"
nmap <leader>vi :tabedit ~/.vimrc<cr>
nmap <leader>so :source $MYVIMRC<cr>

"save & quit
map <leader>w :w<cr>
map <leader>wq :w<cr>:q<cr>

" wrapping and highlight
map <leader>no :let @/ = ""<cr>
map <leader>yw :set wrap<cr>
map <leader>nw :set nowrap<cr>

" Copy the entire buffer into the system register
nmap <leader>co ggVG*y

" Pre-populate a split command with the current directory
nmap <leader>v :vnew <C-r>=escape(expand("%:p:h"), ' ') . '/'<cr>
